#!/bin/bash

# Colorize common commands when we have a colored prompt
if [ "$1" = colored ]; then
	alias ls='ls --color=auto'
	alias dmesg='dmesg --color=auto'
	alias dir='dir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# Pacman aliases
alias pacin="/bin/pacman --needed -Sy"
alias pacup="/bin/pacman -Syu"
alias pacrm="/bin/pacman -R"

# Protection aliases
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
alias su='su -'

# Show hidden files without directory markers but with
# leading backslashes and human readable file sizes
alias la='ls -hAlF'

# Sort ls shortcuts
alias lx='ls -lhXBF' # sort by extension
alias lk='ls -lhSrF' # sort by size
alias lt='ls -lhtrF' # sort by date

# Grub Update Alias
if [ -d "/boot/grub" ]; then
	alias update-grub='grub-mkconfig -o /boot/grub/grub.cfg'
fi

# Extras
alias untar='tar -xvf'
