#!/bin/bash

# Colorize common commands when we have a colored prompt
#if [ "$1" = colored ]; then
#	pass
#else
#	pass
#fi

# Pacman aliases
alias sudo='sudo '
alias pacman='sudo pacman'
alias pacrm='sudo /bin/pacman -R'
alias pacup='sudo /bin/pacman -Syu'
alias pacin='sudo /bin/pacman --needed -Sy'

