#!/usr/bin/env bash

# Clean firefox user profile
if [ -f "/usr/bin/firefox" ]; then
    profile-cleaner f # firefox
fi

# Clean chromium user profile
if [ -f "/usr/bin/chromium" ]; then
    profile-cleaner c # chromium
fi

# Remove profile crashrecovery directorys
if [ -f "/usr/bin/psd" ]; then
    psd clean
fi

# Remove cache crashrecovery directorys
if [ -f "/usr/bin/asd" ]; then
    asd clean
fi

# Remove packages that are no longer installed
sudo pacman --clean

# Use yay to remove orphan packages
yay -c --noconfirm

# Clean pacman & yay cache
yay -Sc --noconfirm
